#!/bin/sh -e

APP=ShowTime
VERSION="0.37.2"

echo "Remove old app"
rm -rf dist/

echo "Remove current build path"
rm -rf build

echo "Generate static files"
ember build --environment=production --output-path=build/

echo "Copy static files to build"
cp package.json main.js build
cp config.json build/
echo "mode=production" > "build/environment"
cp -r assets/ build/assets

echo "Installing packages"
cd build/ && npm install --production && cd ..

echo "Build package using electron-packager"
./node_modules/electron-packager/cli.js build/ $APP --out=dist/ --version=$VERSION --icon=assets/icon.icns --platform=darwin --arch=x64

echo "Remove build path"
rm -rf build/

echo "$APP has been created"