#!/usr/bin/env ruby

require "http"
require "json"

release = ARGV[0]
if release.empty?
  abort "no release"
end

body = ARGV[1]
if release.empty?
  abort "no body"
end

body = HTTP.basic_auth({
  user: "oleander",
  pass: "GPE-gd-9delta53",
}).post("https://api.github.com/repos/oleander/show-time/releases", json: {
  "tag_name": release,
  "target_commitish": "master",
  "name": release,
  "body": body,
  "draft": true,
  "prerelease": true
})

res = JSON.parse(body.to_s)

puts File.join(res.fetch("url"), "assets?name=show-time-mac.zip")

url = res.fetch("upload_url").gsub("{?name}", "?name=show-time-mac.zip")
puts url
p HTTP[{
  "Content-Type" => "application/zip"
}].basic_auth({
  user: "oleander",
  pass: "GPE-gd-9delta53",
}).post(url, {
  body: File.read("dist/ShowTime.zip")
})